export const ROUTES = {
  login: "/login",
  dashboard: "/dashboard",
  products: "/products",
  collections: "/collections",
  boutiques: "/boutiques",
  boutiquesWithTab: (tab: "pending" | "approved" | "rejected" | "all") =>
    `/boutiques?tab=${tab}`,
  jewellerApprovals: "/jeweller-approvals",
  storeReview: (id: string) => `/jeweller-approvals/${id}`,
  users: "/users",
  appointments: "/appointments",
  supportCenter: "/support/chat",
  supportCallbackRequests: "/support/callback-requests",
  occasions: "/occasions",
  categories: "/categories",
  menu: "/menu-categories",
  featured: "/featured-sections",
  offers: "/offers",
  gifts: "/gifts",
  productDetails: (id: string) => `/products/${id}`,
  productActivity: "/products/activity",
  newProduct: "/products/new",
  relationshipSections: "/relationship-sections",
  notifications: "/notifications",
  notificationsSend: "/notifications/send",
  notificationDetail: (id: string) => `/notifications/${id}`,
};
